// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	search.proto

It has these top-level messages:
	SearchRequest
	SearchResponse
	SearchResponseData
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	SearchWord string `protobuf:"bytes,1,opt,name=SearchWord" json:"SearchWord,omitempty"`
	Pagination int64  `protobuf:"varint,2,opt,name=Pagination" json:"Pagination,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SearchRequest) GetSearchWord() string {
	if m != nil {
		return m.SearchWord
	}
	return ""
}

func (m *SearchRequest) GetPagination() int64 {
	if m != nil {
		return m.Pagination
	}
	return 0
}

type SearchResponse struct {
	Search       []*SearchResponseData `protobuf:"bytes,1,rep,name=Search" json:"Search,omitempty"`
	TotalResults string                `protobuf:"bytes,2,opt,name=TotalResults" json:"TotalResults,omitempty"`
	Error        string                `protobuf:"bytes,3,opt,name=Error" json:"Error,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SearchResponse) GetSearch() []*SearchResponseData {
	if m != nil {
		return m.Search
	}
	return nil
}

func (m *SearchResponse) GetTotalResults() string {
	if m != nil {
		return m.TotalResults
	}
	return ""
}

func (m *SearchResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SearchResponseData struct {
	Title  string `protobuf:"bytes,1,opt,name=Title" json:"Title,omitempty"`
	Year   string `protobuf:"bytes,2,opt,name=Year" json:"Year,omitempty"`
	ImdbID string `protobuf:"bytes,3,opt,name=ImdbID" json:"ImdbID,omitempty"`
	Type   string `protobuf:"bytes,4,opt,name=Type" json:"Type,omitempty"`
	Poster string `protobuf:"bytes,5,opt,name=Poster" json:"Poster,omitempty"`
}

func (m *SearchResponseData) Reset()                    { *m = SearchResponseData{} }
func (m *SearchResponseData) String() string            { return proto.CompactTextString(m) }
func (*SearchResponseData) ProtoMessage()               {}
func (*SearchResponseData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SearchResponseData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchResponseData) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *SearchResponseData) GetImdbID() string {
	if m != nil {
		return m.ImdbID
	}
	return ""
}

func (m *SearchResponseData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SearchResponseData) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "grpc.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "grpc.SearchResponse")
	proto.RegisterType((*SearchResponseData)(nil), "grpc.SearchResponseData")
}

func init() { proto.RegisterFile("search.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x8d, 0x49, 0x83, 0x1d, 0xab, 0x87, 0xb1, 0xc8, 0xe2, 0x41, 0x42, 0x4e, 0x39, 0x05,
	0xa9, 0xf8, 0x01, 0x84, 0x7a, 0xe8, 0xc9, 0xb2, 0x0d, 0x88, 0xc7, 0x4d, 0xba, 0xd4, 0x60, 0xcc,
	0xc6, 0xdd, 0xe9, 0x41, 0xf0, 0xe4, 0x27, 0x97, 0xfd, 0x53, 0x68, 0xd0, 0xdb, 0xbe, 0x37, 0x3f,
	0xde, 0xf0, 0x66, 0x61, 0x66, 0xa4, 0xd0, 0xcd, 0x5b, 0x39, 0x68, 0x45, 0x0a, 0x93, 0x9d, 0x1e,
	0x9a, 0xfc, 0x19, 0x2e, 0x36, 0xce, 0xe5, 0xf2, 0x73, 0x2f, 0x0d, 0xe1, 0x2d, 0x80, 0x37, 0x5e,
	0x94, 0xde, 0xb2, 0x28, 0x8b, 0x8a, 0x29, 0x3f, 0x72, 0xec, 0x7c, 0x2d, 0x76, 0x6d, 0x2f, 0xa8,
	0x55, 0x3d, 0x3b, 0xcd, 0xa2, 0x22, 0xe6, 0x47, 0x4e, 0xfe, 0x0d, 0x97, 0x87, 0x40, 0x33, 0xa8,
	0xde, 0x48, 0xbc, 0x83, 0xd4, 0x3b, 0x2c, 0xca, 0xe2, 0xe2, 0x7c, 0xc1, 0x4a, 0xbb, 0xb9, 0x1c,
	0x53, 0x4b, 0x41, 0x82, 0x07, 0x0e, 0x73, 0x98, 0x55, 0x8a, 0x44, 0xc7, 0xa5, 0xd9, 0x77, 0x64,
	0xdc, 0x96, 0x29, 0x1f, 0x79, 0x38, 0x87, 0xc9, 0x93, 0xd6, 0x4a, 0xb3, 0xd8, 0x0d, 0xbd, 0xc8,
	0x7f, 0x22, 0xc0, 0xbf, 0xc1, 0x16, 0xae, 0x5a, 0xea, 0x64, 0xe8, 0xe3, 0x05, 0x22, 0x24, 0xaf,
	0x52, 0xe8, 0x10, 0xef, 0xde, 0x78, 0x0d, 0xe9, 0xea, 0x63, 0x5b, 0xaf, 0x96, 0x21, 0x37, 0x28,
	0xcb, 0x56, 0x5f, 0x83, 0x64, 0x89, 0x67, 0xed, 0xdb, 0xb2, 0x6b, 0x65, 0x48, 0x6a, 0x36, 0xf1,
	0xac, 0x57, 0x8b, 0x47, 0x38, 0xdb, 0x90, 0x6a, 0xde, 0xeb, 0x96, 0xf0, 0xe1, 0x50, 0x1e, 0xaf,
	0xc6, 0xb5, 0xdd, 0xb5, 0x6f, 0xe6, 0xff, 0xdd, 0x22, 0x3f, 0xa9, 0x53, 0xf7, 0x47, 0xf7, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xd5, 0x93, 0x92, 0xb3, 0x01, 0x00, 0x00,
}
